# -*- coding: utf-8 -*-
"""model5_basket_analysis_v5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10G4lIWEhb0MJKa8gmQ9VHKgqdUOjWERx

# Agent 5 v2 — Market Basket Analysis (Enhanced)
### Retail Intelligence Multi-Agent System

**Version:** 2.0.0 — Production-Grade Enhancement  
**Base:** FP-Growth with Variant Normalization, Revenue Weighting, Composite Scoring  
**Output:** `data_basket_rules_v2.csv` + Kafka `[Product_Associations_Updated]` payload

---

| Improvement | What Changed | Business Impact |
|---|---|---|
| Variant Normalization | Strips color/size tokens, collapses 722 variants to canonical codes | Eliminates trivial self-correlated rules |
| Dynamic Support | P78 frequency floor instead of fixed 0.01 | 39% more product coverage (619 → 862 products) |
| Revenue Weighting | Log-normalized total revenue per canonical product | Rules ranked by business value, not just frequency |
| Composite Score | 5-metric weighted score (lift, confidence, leverage, zhang, revenue) | Single production-grade ranking signal |
| Quality Filters | Leverage > 0, Zhang > 0, variant-rule removal, cross-category flagging | Removes low-information and redundant rules |
| Recommendation Engine | Partial match scoring + business impact ranking | Works even with incomplete basket data |

---
**Downstream compatibility:** Kafka payload structure preserved. All v1 output columns maintained + new columns appended.

## Section 1 — Environment Setup
"""

import pandas as pd
import numpy as np
import re
import warnings
import json
import os
import time
from datetime import datetime
from collections import defaultdict

from mlxtend.frequent_patterns import fpgrowth, association_rules
from mlxtend.preprocessing import TransactionEncoder
from sklearn.preprocessing import MinMaxScaler

import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns
import ipywidgets as widgets
from IPython.display import display, HTML, clear_output

warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', 65)
pd.set_option('display.float_format', '{:.4f}'.format)

# ── Paths ──────────────────────────────────────────────────────────────────
DATA_DIR   = os.path.dirname(os.path.abspath('model5_basket_analysis_v2.ipynb'))
CLEAN_PATH = os.path.join(DATA_DIR, 'data_clean.csv')
RFM_PATH   = os.path.join(DATA_DIR, 'data_rfm.csv')
V1_RULES   = os.path.join(DATA_DIR, 'data_basket_rules.csv')       # v1 for comparison

# ── Model hyperparameters ──────────────────────────────────────────────────
# Dynamic support is computed in Section 4. These are the remaining fixed params.
MIN_CONFIDENCE    = 0.12    # lowered from 0.15 to recover more rules at wider coverage
MIN_LIFT          = 1.1     # lowered; composite_score handles quality re-ranking
MAX_ITEMSET_LEN   = 4
MIN_BASKET_SIZE   = 2       # invoices with fewer items are excluded
MIN_PRODUCT_FREQ  = 50      # hard floor: product must appear in ≥50 invoices before dynamic calc
DYNAMIC_SUPPORT_PERCENTILE = 78   # P78 of product frequency distribution

# Composite score weights (must sum to 1.0)
W_LIFT       = 0.30
W_CONFIDENCE = 0.25
W_REVENUE    = 0.25
W_ZHANG      = 0.10
W_LEVERAGE   = 0.10

print('Environment ready.')
print(f'  pandas   : {pd.__version__}')
print(f'  mlxtend  : {__import__("mlxtend").__version__}')
print(f'  sklearn  : {__import__("sklearn").__version__}')

df_raw = pd.read_csv('/content/data_clean.csv')
df_rfm = pd.read_csv('/content/data_rfm.csv')

"""## Section 2 — Data Loading"""

print('Loading data_clean.csv ...')
t0 = time.time()

df_raw = pd.read_csv(
    CLEAN_PATH,
    usecols=['Invoice','StockCode','Description','Quantity','Price',
             'Customer ID','Country','Category','Revenue'],
    dtype={'Invoice': str, 'StockCode': str, 'Customer ID': str}
)
print(f'data_clean : {df_raw.shape}  [{time.time()-t0:.1f}s]')

df_rfm = pd.read_csv(RFM_PATH, dtype={'Customer ID': str})
print(f'data_rfm   : {df_rfm.shape}')

print('\nSample:')
df_raw.head(3)

"""## Section 3 — Improvement 1: Variant Normalization

**Problem:** Rules like `PINK CHERRY LIGHTS → WHITE CHERRY LIGHTS` are trivial. They capture color/size
variants of the same product and inflate rule counts without adding business insight.

**Solution:** Strip color, size, and unit tokens from descriptions to produce a `base_desc`.
Group all variant StockCodes under a single `canonical_code` (the highest-revenue variant).
The transaction matrix is rebuilt using canonical codes.

**Trade-off:** Some genuinely distinct products may share a base description after stripping.
The canonical selection by revenue ensures the most commercially important variant is retained.
"""

# ── Token sets for normalization ───────────────────────────────────────────
COLOR_TOKENS = {
    'RED','BLUE','GREEN','PINK','WHITE','BLACK','YELLOW','PURPLE','ORANGE',
    'SILVER','GOLD','CREAM','GREY','GRAY','BROWN','IVORY','NAVY','TEAL',
    'MINT','CORAL','SAGE','ROSE','LEMON','LILAC','PEACH','AQUA','TURQUOISE',
    'BURGUNDY','MAGENTA','CYAN','LIME','VIOLET','INDIGO','MAUVE','BEIGE','NUDE'
}
SIZE_TOKENS = {
    'SMALL','MEDIUM','LARGE','EXTRA','MINI','GIANT','JUMBO','TALL','SHORT',
    'SLIM','WIDE','NARROW','PETITE','OVERSIZED','XS','SM','MD','LG','XL'
}
SIZE_UNIT_RE = re.compile(r'\b\d+\s*(CM|MM|IN|INCH|L|ML|OZ|G|KG|PCS|SET|PC|PIECE|PACK)\b', re.I)
STANDALONE_NUM_RE = re.compile(r'(?<![A-Z])\b\d+\b(?![A-Z])')
PUNCT_RE = re.compile(r'[^A-Z0-9\s]')

def normalize_description(desc: str) -> str:
    """
    Strips color, size, unit, and punctuation tokens from a product description
    to produce a canonical base form for variant grouping.
    """
    if pd.isna(desc):
        return 'UNKNOWN'
    d = str(desc).upper().strip()
    d = PUNCT_RE.sub(' ', d)
    d = SIZE_UNIT_RE.sub(' ', d)
    tokens = d.split()
    tokens = [t for t in tokens if t not in COLOR_TOKENS
                                and t not in SIZE_TOKENS
                                and not STANDALONE_NUM_RE.fullmatch(t)]
    d = ' '.join(tokens)
    d = re.sub(r'\s+', ' ', d).strip()
    return d if d else 'UNKNOWN'

# Apply normalization
df_raw['base_desc'] = df_raw['Description'].apply(normalize_description)

# ── Build canonical product mapping ───────────────────────────────────────
# For each base_desc group, the canonical code is the StockCode with highest total revenue.
# This preserves the most commercially significant variant.
revenue_per_code = df_raw.groupby('StockCode')['Revenue'].sum().rename('code_revenue')
df_raw['code_revenue'] = df_raw['StockCode'].map(revenue_per_code)

canonical_df = (
    df_raw.drop_duplicates('StockCode')[['StockCode', 'base_desc', 'code_revenue']]
    .sort_values('code_revenue', ascending=False)
    .groupby('base_desc')
    .first()
    .reset_index()[['base_desc', 'StockCode']]
    .rename(columns={'StockCode': 'canonical_code'})
)

base_to_canonical = canonical_df.set_index('base_desc')['canonical_code'].to_dict()
code_to_base      = df_raw.drop_duplicates('StockCode').set_index('StockCode')['base_desc'].to_dict()
code_to_canonical = {code: base_to_canonical[base] for code, base in code_to_base.items()}

df_raw['canonical_code'] = df_raw['StockCode'].map(code_to_canonical)

n_original  = df_raw['StockCode'].nunique()
n_canonical = df_raw['canonical_code'].nunique()
n_collapsed = n_original - n_canonical

print('Variant Normalization Results:')
print(f'  Original StockCodes   : {n_original:,}')
print(f'  Canonical codes       : {n_canonical:,}')
print(f'  Variants collapsed    : {n_collapsed:,}  ({n_collapsed/n_original*100:.1f}%)')

# Show example variant groups
variant_groups = (
    df_raw.drop_duplicates('StockCode')
    .groupby('base_desc')['StockCode'].count()
)
multi_variant = variant_groups[variant_groups > 1].sort_values(ascending=False)
print(f'\nTop 10 variant groups (collapsed into 1 canonical code each):')
print(multi_variant.head(10).to_string())

"""## Section 4 — Improvement 2: Dynamic Support Threshold

**Problem:** Fixed `min_support=0.01` (338 transactions) is arbitrary. It excluded 57% of products
and missed many legitimate associations among mid-frequency items.

**Solution:** Use the **P78 of the product invoice-frequency distribution** as the dynamic floor.
This is data-driven — it adapts to the actual distribution of the dataset rather than a hand-tuned constant.

**Trade-off:** Lower support means more itemsets and longer FP-Growth runtime. Compensated by stricter
quality filters downstream (leverage, zhang, composite score).
"""

# ── Filter: multi-item baskets only ───────────────────────────────────────
basket_sz = df_raw.groupby('Invoice')['canonical_code'].transform('count')
df_filtered = df_raw[basket_sz >= MIN_BASKET_SIZE].copy()

# ── Per-invoice unique product set (avoid counting same product twice per invoice) ──
invoice_product_sets = df_filtered.groupby('Invoice')['canonical_code'].apply(set)
product_freq = invoice_product_sets.explode().value_counts()
n_tx = df_filtered['Invoice'].nunique()

# ── Dynamic support calculation ────────────────────────────────────────────
# Step 1: Apply hard floor
qualifying_products = product_freq[product_freq >= MIN_PRODUCT_FREQ]

# Step 2: Compute P78 from qualifying products' frequency distribution
dynamic_min_abs  = int(np.percentile(qualifying_products.values, DYNAMIC_SUPPORT_PERCENTILE))
MIN_SUPPORT_DYN  = round(dynamic_min_abs / n_tx, 4)

# Apply dynamic threshold
valid_products = product_freq[product_freq >= dynamic_min_abs].index
df_filtered = df_filtered[df_filtered['canonical_code'].isin(valid_products)]

print('Dynamic Support Calculation:')
print(f'  P{DYNAMIC_SUPPORT_PERCENTILE} of qualifying product frequencies : {dynamic_min_abs} invoices')
print(f'  Computed min_support                     : {MIN_SUPPORT_DYN}')
print(f'  Total valid invoices                     : {df_filtered["Invoice"].nunique():,}')
print(f'  Products in model (v1)                   : 619')
print(f'  Products in model (v2)                   : {len(valid_products):,}')
print(f'  Coverage improvement                     : +{((len(valid_products)/619)-1)*100:.1f}%')

# ── Support threshold comparison plot ─────────────────────────────────────
fig, ax = plt.subplots(figsize=(11, 4))
freq_vals = qualifying_products.sort_values(ascending=False).reset_index(drop=True)
ax.plot(freq_vals.values, color='#4A90D9', linewidth=1.5, label='Product frequency')
ax.axhline(dynamic_min_abs, color='#2ECC71', linestyle='--', linewidth=2,
           label=f'Dynamic threshold (P{DYNAMIC_SUPPORT_PERCENTILE}): {dynamic_min_abs} → support={MIN_SUPPORT_DYN}')
ax.axhline(338, color='#E74C3C', linestyle='--', linewidth=2,
           label='v1 fixed threshold: 338 → support=0.01')
ax.fill_between(range(len(freq_vals)), freq_vals.values, dynamic_min_abs,
                where=freq_vals.values >= dynamic_min_abs, alpha=0.15, color='#2ECC71',
                label=f'Products included in v2: {(freq_vals.values >= dynamic_min_abs).sum()}')
ax.set_xlabel('Products ranked by frequency')
ax.set_ylabel('Invoice count')
ax.set_title('Dynamic vs Fixed Support Threshold — Product Coverage')
ax.legend(fontsize=9)
ax.set_yscale('log')
plt.tight_layout()
plt.savefig(os.path.join(DATA_DIR, 'plot_v2_support_threshold.png'), dpi=150, bbox_inches='tight')
plt.show()
print('Plot saved.')

"""## Section 5 — Improvement 3: Revenue-Aware Weighting

**Problem:** A rule involving a £0.50 sticker and a £25 lamp is treated identically to
a rule involving two £25 items. Business impact is ignored.

**Solution:** Compute `rev_weight` per canonical product using log-normalized total revenue.
Log normalization prevents high-revenue outliers from dominating. Rule-level revenue weight
is the mean weight across all antecedent and consequent items.
"""

# ── Revenue per canonical code ─────────────────────────────────────────────
revenue_stats = (
    df_filtered
    .groupby('canonical_code')
    .agg(
        total_revenue=('Revenue', 'sum'),
        avg_price=('Price', 'mean'),
        total_qty=('Quantity', 'sum'),
        invoice_count=('Invoice', 'nunique')
    )
    .reset_index()
)

# Log-normalized revenue weight in [0, 1]
# Using log1p to handle zero revenue edge cases and compress the long tail.
max_log_rev = np.log1p(revenue_stats['total_revenue'].max())
revenue_stats['rev_weight'] = np.log1p(revenue_stats['total_revenue']) / max_log_rev

rev_weight_map  = revenue_stats.set_index('canonical_code')['rev_weight'].to_dict()
total_rev_map   = revenue_stats.set_index('canonical_code')['total_revenue'].to_dict()

# ── Canonical product metadata table ─────────────────────────────────────
canonical_meta = (
    df_filtered
    .drop_duplicates('canonical_code')[['canonical_code', 'base_desc', 'Category']]
    .merge(revenue_stats[['canonical_code','total_revenue','avg_price','rev_weight']], on='canonical_code', how='left')
    .set_index('canonical_code')
)

print('Revenue Weight Distribution (per canonical product):')
print(revenue_stats['rev_weight'].describe().to_string())
print()
print('Top 10 products by revenue weight:')
top_rev = revenue_stats.nlargest(10, 'total_revenue')[['canonical_code','total_revenue','avg_price','rev_weight']]
top_rev['base_desc'] = top_rev['canonical_code'].map(canonical_meta['base_desc'])
print(top_rev[['base_desc','total_revenue','avg_price','rev_weight']].to_string(index=False))

# Revenue weight distribution plot
fig, axes = plt.subplots(1, 2, figsize=(13, 4))
axes[0].hist(revenue_stats['total_revenue'], bins=50, color='#E74C3C', edgecolor='white')
axes[0].set_title('Raw Revenue Distribution (skewed)')
axes[0].set_xlabel('Total Revenue')
axes[0].xaxis.set_major_formatter(plt.FuncFormatter(lambda x, _: f'{x/1000:.0f}K'))
axes[1].hist(revenue_stats['rev_weight'], bins=50, color='#2ECC71', edgecolor='white')
axes[1].set_title('Log-Normalized Revenue Weight (used in model)')
axes[1].set_xlabel('rev_weight [0, 1]')
plt.suptitle('Revenue Weight Normalization', fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig(os.path.join(DATA_DIR, 'plot_v2_revenue_weight.png'), dpi=150, bbox_inches='tight')
plt.show()
print('Plot saved.')

"""## Section 6 — FP-Growth on Canonical Products"""

# Build transactions using canonical codes.
# Deduplicate within each invoice: if two variants of same product appear in one order,
# they become a single canonical item — preventing inflated co-occurrence counts.

print('Building canonical transaction lists ...')
t0 = time.time()

transactions = (
    df_filtered
    .groupby('Invoice')['canonical_code']
    .apply(lambda x: list(set(x)))      # set() deduplicates variants within same invoice
    .tolist()
)
# Keep only multi-item canonical baskets
transactions = [t for t in transactions if len(t) >= 2]
n_tx_valid   = len(transactions)

print(f'Transaction lists built in {time.time()-t0:.1f}s')
print(f'Valid canonical transactions : {n_tx_valid:,}')

print('\nEncoding one-hot matrix ...')
t0 = time.time()
te = TransactionEncoder()
te_arr = te.fit_transform(transactions)
df_enc = pd.DataFrame(te_arr, columns=te.columns_)
print(f'Matrix shape : {df_enc.shape}  [{time.time()-t0:.1f}s]')
print(f'Density      : {df_enc.values.mean():.5f}')

print(f'Running FP-Growth ...')
print(f'  min_support  = {MIN_SUPPORT_DYN}  (>= {dynamic_min_abs} canonical transactions)')
print(f'  max_len      = {MAX_ITEMSET_LEN}')
print()

t0 = time.time()
freq_itemsets = fpgrowth(
    df_enc,
    min_support=MIN_SUPPORT_DYN,
    use_colnames=True,
    max_len=MAX_ITEMSET_LEN,
    verbose=0
)
freq_itemsets['length']        = freq_itemsets['itemsets'].apply(len)
freq_itemsets['support_count'] = (freq_itemsets['support'] * n_tx_valid).round().astype(int)

elapsed = time.time() - t0
print(f'FP-Growth completed in {elapsed:.1f}s')
print(f'Frequent itemsets : {len(freq_itemsets):,}')
print()
print('Itemset count by length:')
print(freq_itemsets['length'].value_counts().sort_index().to_string())
print()

# Compare with v1
print('v1 → v2 itemset comparison:')
print(f'  v1 itemsets: 998   |   v2 itemsets: {len(freq_itemsets):,}')
print(f'  Improvement: +{((len(freq_itemsets)/998)-1)*100:.0f}%')

"""## Section 7 — Improvement 4: Rule Quality Filtering + Composite Score

**Multi-metric filtering pipeline:**
1. `lift >= 1.1` — rule fires more than random chance
2. `leverage > 0` — items co-occur more frequently than if independent
3. `zhangs_metric > 0` — positive association (not a substitution effect)
4. Variant-rule removal — strips antecedent/consequent overlapping base descriptions
5. Cross-category flagging — marks rules spanning multiple categories (higher business value)

**Composite score formula:**
```
composite_score = 0.30 × norm(lift)
               + 0.25 × norm(confidence)
               + 0.25 × norm(revenue_weight)
               + 0.10 × norm(zhang)
               + 0.10 × norm(leverage)
```
All metrics min-max normalized to [0, 1] before combining.
"""

print('Generating association rules ...')
t0 = time.time()

rules = association_rules(
    freq_itemsets,
    metric='confidence',
    min_threshold=MIN_CONFIDENCE,
    num_itemsets=len(freq_itemsets)
)
print(f'Raw rules generated  : {len(rules):,}  [{time.time()-t0:.1f}s]')

# ── Filter 1: Lift ─────────────────────────────────────────────────────────
before = len(rules)
rules = rules[rules['lift'] >= MIN_LIFT].copy()
print(f'After lift filter    : {len(rules):,}  (removed {before-len(rules):,})')

# ── Filter 2: Leverage ────────────────────────────────────────────────────
before = len(rules)
rules = rules[rules['leverage'] > 0].copy()
print(f'After leverage filter: {len(rules):,}  (removed {before-len(rules):,})')

# ── Filter 3: Zhang's metric ──────────────────────────────────────────────
# Zhang's metric = 0 means no association; <0 = substitution. We want positive association only.
before = len(rules)
rules = rules[rules['zhangs_metric'] > 0].copy()
print(f'After zhang filter   : {len(rules):,}  (removed {before-len(rules):,})')

# ── Filter 4: Variant rules ───────────────────────────────────────────────
# Remove rules where the antecedent and consequent share a base_desc.
# This catches cases where normalization did not fully collapse a variant group.
def has_variant_overlap(ant_set, con_set):
    ant_bases = {code_to_base.get(c, c) for c in ant_set}
    con_bases = {code_to_base.get(c, c) for c in con_set}
    return len(ant_bases & con_bases) > 0

before = len(rules)
rules['is_variant_rule'] = rules.apply(
    lambda r: has_variant_overlap(r['antecedents'], r['consequents']), axis=1
)
rules = rules[~rules['is_variant_rule']].drop(columns='is_variant_rule')
print(f'After variant filter : {len(rules):,}  (removed {before-len(rules):,})')

print(f'\nFinal rule count: {len(rules):,}')

# ── Category flags ─────────────────────────────────────────────────────────
def get_categories(itemset):
    return frozenset(
        canonical_meta.loc[c, 'Category']
        for c in itemset
        if c in canonical_meta.index
    )

rules['ant_cats'] = rules['antecedents'].apply(get_categories)
rules['con_cats'] = rules['consequents'].apply(get_categories)
rules['is_cross_category']  = rules.apply(lambda r: len(r['ant_cats'] & r['con_cats']) == 0, axis=1)
rules['same_category_only'] = rules.apply(
    lambda r: r['ant_cats'] == r['con_cats'] and len(r['ant_cats']) == 1, axis=1
)

print(f'Cross-category rules : {rules["is_cross_category"].sum():,}')
print(f'Same-category rules  : {rules["same_category_only"].sum():,}')
print()

# ── Revenue weight per rule ────────────────────────────────────────────────
def compute_rule_rev_weight(ant_set, con_set):
    """
    Mean log-normalized revenue weight across all items in the rule.
    High revenue items pull the rule score up.
    """
    items   = list(ant_set) + list(con_set)
    weights = [rev_weight_map.get(c, 0.01) for c in items]
    return float(np.mean(weights))

rules['revenue_weight'] = rules.apply(
    lambda r: compute_rule_rev_weight(r['antecedents'], r['consequents']), axis=1
)

# ── Composite score ────────────────────────────────────────────────────────
# Normalize each metric independently to [0, 1] using MinMaxScaler,
# then apply business-driven weights.

metrics_to_normalize = ['lift', 'confidence', 'leverage', 'zhangs_metric', 'revenue_weight']
scaler = MinMaxScaler()
norm_values = scaler.fit_transform(rules[metrics_to_normalize])
norm_df = pd.DataFrame(
    norm_values,
    columns=[f'norm_{m}' for m in metrics_to_normalize],
    index=rules.index
)
rules = pd.concat([rules, norm_df], axis=1)

rules['composite_score'] = (
    W_LIFT       * rules['norm_lift'] +
    W_CONFIDENCE * rules['norm_confidence'] +
    W_REVENUE    * rules['norm_revenue_weight'] +
    W_ZHANG      * rules['norm_zhangs_metric'] +
    W_LEVERAGE   * rules['norm_leverage']
)

# ── Human-readable columns ────────────────────────────────────────────────
def rule_strength(lift: float) -> str:
    if lift >= 5.0: return 'Very Strong'
    if lift >= 3.0: return 'Strong'
    if lift >= 2.0: return 'Moderate'
    return 'Weak'

def score_tier(score: float) -> str:
    if score >= 0.60: return 'Tier 1'
    if score >= 0.40: return 'Tier 2'
    if score >= 0.25: return 'Tier 3'
    return 'Tier 4'

def to_desc(itemset):
    return ' | '.join(
        canonical_meta.loc[c, 'base_desc'] if c in canonical_meta.index else c
        for c in sorted(itemset)
    )

rules['antecedents_str']  = rules['antecedents'].apply(lambda x: ', '.join(sorted(x)))
rules['consequents_str']  = rules['consequents'].apply(lambda x: ', '.join(sorted(x)))
rules['antecedents_desc'] = rules['antecedents'].apply(to_desc)
rules['consequents_desc'] = rules['consequents'].apply(to_desc)
rules['strength']         = rules['lift'].apply(rule_strength)
rules['score_tier']       = rules['composite_score'].apply(score_tier)
rules.insert(0, 'rule_id', [f'RULE_{str(i).zfill(5)}' for i in range(len(rules))])
rules['generated_at']     = datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ')

print('Composite Scoring Complete:')
print(f'  Score range  : {rules["composite_score"].min():.4f} – {rules["composite_score"].max():.4f}')
print(f'  Score mean   : {rules["composite_score"].mean():.4f}')
print()
print('Score tier distribution:')
print(rules['score_tier'].value_counts().sort_index().to_string())

print('Top 15 Rules by Composite Score:')
display_cols = ['rule_id','antecedents_desc','consequents_desc',
                'support','confidence','lift','revenue_weight','composite_score','score_tier']
rules.nlargest(15, 'composite_score')[display_cols]

"""## Section 8 — Rule Quality Visualization"""

fig = plt.figure(figsize=(18, 13))
fig.suptitle('Agent 5 v2 — Rule Quality Analysis', fontsize=16, fontweight='bold')
gs  = gridspec.GridSpec(3, 3, figure=fig, hspace=0.5, wspace=0.35)

# ── 1: Support vs Confidence (colored by composite_score) ─────────────────
ax1 = fig.add_subplot(gs[0, :])
sc  = ax1.scatter(
    rules['support'], rules['confidence'],
    c=rules['composite_score'], cmap='RdYlGn', alpha=0.55, s=20,
    vmin=rules['composite_score'].quantile(0.05),
    vmax=rules['composite_score'].quantile(0.95)
)
plt.colorbar(sc, ax=ax1, label='Composite Score')
ax1.axhline(MIN_CONFIDENCE, color='red', linestyle='--', alpha=0.5, label=f'min_confidence={MIN_CONFIDENCE}')
ax1.axvline(MIN_SUPPORT_DYN, color='blue', linestyle='--', alpha=0.5, label=f'min_support={MIN_SUPPORT_DYN}')
ax1.set_xlabel('Support')
ax1.set_ylabel('Confidence')
ax1.set_title('Support vs Confidence — color = Composite Score')
ax1.legend(fontsize=9)

# ── 2: Composite score distribution ───────────────────────────────────────
ax2 = fig.add_subplot(gs[1, 0])
ax2.hist(rules['composite_score'], bins=40, color='#4A90D9', edgecolor='white')
ax2.axvline(rules['composite_score'].mean(), color='red', linestyle='--',
            label=f'Mean: {rules["composite_score"].mean():.3f}')
ax2.set_title('Composite Score Distribution')
ax2.set_xlabel('composite_score')
ax2.legend()

# ── 3: Revenue weight vs Lift scatter ─────────────────────────────────────
ax3 = fig.add_subplot(gs[1, 1])
sc3 = ax3.scatter(rules['revenue_weight'], rules['lift'],
                  c=rules['confidence'], cmap='Blues', alpha=0.4, s=15)
plt.colorbar(sc3, ax=ax3, label='Confidence')
ax3.set_xlabel('Revenue Weight')
ax3.set_ylabel('Lift')
ax3.set_title('Revenue Weight vs Lift')
ax3.set_yscale('log')

# ── 4: Score tier breakdown ────────────────────────────────────────────────
ax4 = fig.add_subplot(gs[1, 2])
tier_counts = rules['score_tier'].value_counts().sort_index()
tier_colors = ['#2ECC71','#3498DB','#F39C12','#E74C3C']
bars = ax4.bar(tier_counts.index, tier_counts.values, color=tier_colors, edgecolor='white')
ax4.set_title('Score Tier Breakdown')
ax4.set_ylabel('Number of Rules')
for bar, val in zip(bars, tier_counts.values):
    ax4.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 5,
             str(val), ha='center', va='bottom', fontweight='bold')

# ── 5: Cross-category vs Same-category distribution ───────────────────────
ax5 = fig.add_subplot(gs[2, 0])
cat_type_counts = pd.Series({
    'Cross-Category': rules['is_cross_category'].sum(),
    'Same-Category' : rules['same_category_only'].sum(),
    'Mixed'         : len(rules) - rules['is_cross_category'].sum() - rules['same_category_only'].sum()
})
ax5.bar(cat_type_counts.index, cat_type_counts.values,
        color=['#9B59B6','#E74C3C','#95A5A6'], edgecolor='white')
ax5.set_title('Rule Category Span')
ax5.set_ylabel('Count')
ax5.tick_params(axis='x', rotation=15)
for i, v in enumerate(cat_type_counts.values):
    ax5.text(i, v + 5, str(v), ha='center', fontweight='bold')

# ── 6: Zhang metric distribution ──────────────────────────────────────────
ax6 = fig.add_subplot(gs[2, 1])
ax6.hist(rules['zhangs_metric'].clip(lower=-1, upper=1), bins=40,
         color='#E67E22', edgecolor='white')
ax6.axvline(0, color='black', linestyle='--', linewidth=1)
ax6.set_title("Zhang's Metric Distribution")
ax6.set_xlabel("zhang's metric")

# ── 7: v1 vs v2 side-by-side comparison ───────────────────────────────────
ax7 = fig.add_subplot(gs[2, 2])
comparison = pd.DataFrame({
    'Metric'  : ['Products', 'Itemsets', 'Rules', 'Mean Lift', 'Mean Conf'],
    'v1'      : [619, 998, 961, 12.62, 0.42],
    'v2'      : [len(valid_products), len(freq_itemsets), len(rules),
                 round(rules['lift'].mean(), 2), round(rules['confidence'].mean(), 2)]
})
x = np.arange(len(comparison))
w = 0.35
ax7.bar(x - w/2, comparison['v1'], w, label='v1', color='#BDC3C7', edgecolor='white')
ax7.bar(x + w/2, comparison['v2'], w, label='v2', color='#4A90D9', edgecolor='white')
ax7.set_xticks(x)
ax7.set_xticklabels(comparison['Metric'], rotation=15, fontsize=8)
ax7.set_title('v1 vs v2 Comparison')
ax7.legend()
ax7.set_yscale('log')

plt.savefig(os.path.join(DATA_DIR, 'plot_v2_rule_quality.png'), dpi=150, bbox_inches='tight')
plt.show()
print('Plot saved.')

# ── Lift heatmap: top 20 canonical products ─────────────────────────────
pair_rules = rules[
    (rules['antecedents'].apply(len) == 1) &
    (rules['consequents'].apply(len) == 1)
].copy()
pair_rules['ant_item'] = pair_rules['antecedents'].apply(lambda x: list(x)[0])
pair_rules['con_item'] = pair_rules['consequents'].apply(lambda x: list(x)[0])

top20_codes = (
    df_filtered.groupby('canonical_code')['Invoice'].nunique()
    .sort_values(ascending=False).head(20).index.tolist()
)
top20_desc = {
    c: canonical_meta.loc[c, 'base_desc'][:28]
    if c in canonical_meta.index else c
    for c in top20_codes
}

heat_rules = pair_rules[
    pair_rules['ant_item'].isin(top20_codes) &
    pair_rules['con_item'].isin(top20_codes)
]
if len(heat_rules) > 0:
    pivot = heat_rules.pivot_table(
        index='ant_item', columns='con_item', values='composite_score', fill_value=0
    )
    pivot.index   = [top20_desc.get(i, i) for i in pivot.index]
    pivot.columns = [top20_desc.get(c, c) for c in pivot.columns]

    fig, ax = plt.subplots(figsize=(14, 10))
    sns.heatmap(pivot, annot=True, fmt='.2f', cmap='YlOrRd',
                linewidths=0.3, ax=ax, cbar_kws={'label': 'Composite Score'})
    ax.set_title('Composite Score Heatmap — Top 20 Products', fontsize=13, fontweight='bold')
    ax.tick_params(axis='x', rotation=45, labelsize=8)
    ax.tick_params(axis='y', rotation=0, labelsize=8)
    plt.tight_layout()
    plt.savefig(os.path.join(DATA_DIR, 'plot_v2_heatmap.png'), dpi=150, bbox_inches='tight')
    plt.show()
    print('Heatmap saved.')

"""## Section 9 — Category-Level Rules"""

print('Building category-level rules (for Inventory Reorder Agent A7) ...')

cat_transactions = (
    df_filtered
    .copy() # Make a copy to avoid SettingWithCopyWarning
    .assign(Category=lambda x: x['Category'].fillna('Unknown').astype(str))
    .groupby('Invoice')['Category']
    .apply(lambda cats: list(set(cats))) # Now all cats are strings
    .tolist()
)
cat_transactions = [t for t in cat_transactions if len(t) >= 2]

te_cat = TransactionEncoder()
df_cat_enc = pd.DataFrame(te_cat.fit_transform(cat_transactions), columns=te_cat.columns_)

cat_fi = fpgrowth(df_cat_enc, min_support=0.02, use_colnames=True, max_len=3)
cat_rules = association_rules(cat_fi, metric='confidence', min_threshold=0.10,
                               num_itemsets=len(cat_fi))
cat_rules = cat_rules[
    (cat_rules['lift'] >= 1.1) & (cat_rules['zhangs_metric'] > 0)
].copy()

# Revenue enrichment at category level
cat_revenue = df_filtered.groupby('Category')['Revenue'].sum()
max_cat_rev = cat_revenue.max()
cat_rev_weight = np.log1p(cat_revenue) / np.log1p(max_cat_rev)

def cat_rule_revenue(ant, con):
    items = list(ant) + list(con)
    # Ensure category codes are strings for dictionary lookup if they somehow became numbers
    weights = [cat_rev_weight.get(str(c), 0.01) for c in items]
    return float(np.mean(weights))

cat_rules['antecedents_str'] = cat_rules['antecedents'].apply(lambda x: ' + '.join(sorted(x)))
cat_rules['consequents_str'] = cat_rules['consequents'].apply(lambda x: ' + '.join(sorted(x)))
cat_rules['revenue_weight']  = cat_rules.apply(
    lambda r: cat_rule_revenue(r['antecedents'], r['consequents']), axis=1
)
cat_rules.insert(0, 'rule_id', [f'CAT_RULE_{str(i).zfill(4)}' for i in range(len(cat_rules))])

print(f'Category rules: {len(cat_rules):,}')
cat_rules.nlargest(10, 'lift')[['rule_id','antecedents_str','consequents_str','support','confidence','lift','revenue_weight']]

"""## Section 10 — RFM Segment Enrichment"""

def assign_rfm_segment(row):
    r, f, m = row['Recency'], row['Frequency'], row['Monetary']
    r_s = 4 if r <= 30  else 3 if r <= 90  else 2 if r <= 180 else 1
    f_s = 4 if f >= 20  else 3 if f >= 10  else 2 if f >= 4   else 1
    m_s = 4 if m >= 5000 else 3 if m >= 1500 else 2 if m >= 500 else 1
    total = r_s + f_s + m_s
    if total >= 10: return 'Champions'
    if total >= 8:  return 'Loyal'
    if total >= 6:  return 'At Risk'
    return 'Lost'

df_rfm['segment'] = df_rfm.apply(assign_rfm_segment, axis=1)
print('Segment distribution:', df_rfm['segment'].value_counts().to_dict())

df_enriched = df_filtered.merge(
    df_rfm[['Customer ID','segment']], on='Customer ID', how='left'
)
df_enriched['segment'].fillna('Unknown', inplace=True)

segment_rules_store = {}
for segment in ['Champions','Loyal','At Risk','Lost']:
    seg_df  = df_enriched[df_enriched['segment'] == segment]
    n_inv   = seg_df['Invoice'].nunique()
    if n_inv < 200:
        print(f'  [{segment}] skipped ({n_inv} invoices)')
        continue

    seg_tx = [
        list(set(items))
        for items in seg_df.groupby('Invoice')['canonical_code'].apply(list).tolist()
        if len(set(items)) >= 2
    ]
    if len(seg_tx) < 100:
        continue

    te_s   = TransactionEncoder()
    df_s   = pd.DataFrame(te_s.fit_transform(seg_tx), columns=te_s.columns_)
    ada_s  = max(0.02, MIN_SUPPORT_DYN * (200 / n_inv))
    fi_s   = fpgrowth(df_s, min_support=ada_s, use_colnames=True, max_len=3, verbose=0)
    if len(fi_s) == 0:
        continue

    r_s = association_rules(fi_s, metric='confidence', min_threshold=MIN_CONFIDENCE,
                             num_itemsets=len(fi_s))
    r_s = r_s[
        (r_s['lift'] >= MIN_LIFT) & (r_s['leverage'] > 0) & (r_s['zhangs_metric'] > 0)
    ].copy()
    r_s['segment']         = segment
    r_s['antecedents_str'] = r_s['antecedents'].apply(lambda x: ', '.join(sorted(x)))
    r_s['consequents_str'] = r_s['consequents'].apply(lambda x: ', '.join(sorted(x)))
    r_s['revenue_weight']  = r_s.apply(
        lambda row: compute_rule_rev_weight(row['antecedents'], row['consequents']), axis=1
    )
    segment_rules_store[segment] = r_s
    print(f'  [{segment}] {n_inv:>6,} invoices | {len(r_s):>4,} rules | support>={ada_s:.4f}')

df_segment_rules = (
    pd.concat(segment_rules_store.values(), ignore_index=True)
    if segment_rules_store else pd.DataFrame()
)
print(f'\nTotal segment rules: {len(df_segment_rules):,}')

"""## Section 11 — Model Performance Summary"""

all_rule_items = set()
for _, row in rules.iterrows():
    all_rule_items.update(row['antecedents'])
    all_rule_items.update(row['consequents'])

total_products = df_enc.shape[1]
coverage_pct   = len(all_rule_items) / total_products * 100

print('=' * 60)
print('  AGENT 5 v2 — ENHANCED MBA — MODEL SUMMARY')
print('=' * 60)
print(f'  Variants collapsed            : 722 (15.6% of StockCodes)')
print(f'  Canonical products in model   : {total_products:>8,}')
print(f'  Valid transactions (canonical): {n_tx_valid:>8,}')
print(f'  Frequent itemsets             : {len(freq_itemsets):>8,}   (v1: 998   | +{((len(freq_itemsets)/998)-1)*100:.0f}%)')
print(f'  Association rules             : {len(rules):>8,}   (v1: 961   | +{((len(rules)/961)-1)*100:.0f}%)')
print(f'  Category rules                : {len(cat_rules):>8,}')
print(f'  Segment-specific rules        : {len(df_segment_rules):>8,}')
print(f'  Product coverage              : {coverage_pct:>7.1f}%')
print(f'  Cross-category rules          : {rules["is_cross_category"].sum():>8,}')
print()
print('  Rule Quality Metrics:')
print(f'    Support    — mean: {rules["support"].mean():.4f}  max: {rules["support"].max():.4f}')
print(f'    Confidence — mean: {rules["confidence"].mean():.4f}  max: {rules["confidence"].max():.4f}')
print(f'    Lift       — mean: {rules["lift"].mean():.4f}  max: {rules["lift"].max():.4f}')
print(f'    Leverage   — mean: {rules["leverage"].mean():.6f}')
print(f'    Zhang      — mean: {rules["zhangs_metric"].mean():.4f}')
print(f'    Composite  — mean: {rules["composite_score"].mean():.4f}  max: {rules["composite_score"].max():.4f}')
print()
print('  Dynamic Support:')
print(f'    v1 fixed  : 0.0100  (338 transactions)')
print(f'    v2 dynamic: {MIN_SUPPORT_DYN}  ({dynamic_min_abs} transactions, P{DYNAMIC_SUPPORT_PERCENTILE})')
print()
print('  Score Tiers:')
for tier, cnt in rules['score_tier'].value_counts().sort_index().items():
    print(f'    {tier}: {cnt:,} rules')
print('=' * 60)

"""## Section 12 — Save All Outputs"""

# ── Export columns (v1 compatible + new v2 columns) ───────────────────────
export_cols = [
    # v1 compatible
    'rule_id', 'antecedents_str', 'consequents_str',
    'antecedents_desc', 'consequents_desc',
    'support', 'confidence', 'lift',
    'leverage', 'conviction', 'zhangs_metric',
    'strength', 'generated_at',
    # v2 new
    'revenue_weight', 'composite_score', 'score_tier',
    'is_cross_category', 'same_category_only',
    'norm_lift', 'norm_confidence', 'norm_revenue_weight',
    'norm_zhangs_metric', 'norm_leverage'
]

rules_export = rules[[c for c in export_cols if c in rules.columns]].copy()

paths = {
    'rules'     : os.path.join(DATA_DIR, 'data_basket_rules_v2.csv'),
    'cat_rules' : os.path.join(DATA_DIR, 'data_basket_category_rules_v2.csv'),
    'seg_rules' : os.path.join(DATA_DIR, 'data_basket_segment_rules_v2.csv'),
    'itemsets'  : os.path.join(DATA_DIR, 'data_basket_itemsets_v2.csv'),
    'canonical' : os.path.join(DATA_DIR, 'data_canonical_products.csv'),
    'kafka'     : os.path.join(DATA_DIR, 'kafka_payload_v2.json')
}

rules_export.to_csv(paths['rules'], index=False)
print(f'Saved: data_basket_rules_v2.csv           ({len(rules_export):,} rules)')

cat_rules[['rule_id','antecedents_str','consequents_str',
           'support','confidence','lift','revenue_weight']].to_csv(paths['cat_rules'], index=False)
print(f'Saved: data_basket_category_rules_v2.csv  ({len(cat_rules):,} rules)')

if len(df_segment_rules) > 0:
    df_segment_rules[[
        'segment','antecedents_str','consequents_str',
        'support','confidence','lift','revenue_weight'
    ]].to_csv(paths['seg_rules'], index=False)
    print(f'Saved: data_basket_segment_rules_v2.csv   ({len(df_segment_rules):,} rules)')

fi_exp = freq_itemsets.copy()
fi_exp['itemsets'] = fi_exp['itemsets'].apply(lambda x: ', '.join(sorted(x)))
fi_exp.to_csv(paths['itemsets'], index=False)
print(f'Saved: data_basket_itemsets_v2.csv        ({len(fi_exp):,} itemsets)')

canonical_meta.reset_index().to_csv(paths['canonical'], index=False)
print(f'Saved: data_canonical_products.csv        ({len(canonical_meta):,} products)')

"""## Section 13 — Kafka Event Payload (v2, Backward Compatible)"""

def build_kafka_payload_v2(rules_df, cat_rules_df, top_n=50):
    """
    Builds [Product_Associations_Updated] Kafka event.
    v2 adds: composite_score, revenue_weight, score_tier, is_cross_category.
    Backward compatible: all v1 fields preserved.
    """
    top_rules = rules_df.nlargest(top_n, 'composite_score')

    item_rules_payload = []
    for _, row in top_rules.iterrows():
        item_rules_payload.append({
            # v1 fields
            'rule_id'         : row['rule_id'],
            'antecedents'     : row['antecedents_str'].split(', '),
            'consequents'     : row['consequents_str'].split(', '),
            'antecedents_desc': row.get('antecedents_desc', ''),
            'consequents_desc': row.get('consequents_desc', ''),
            'support'         : round(float(row['support']), 6),
            'confidence'      : round(float(row['confidence']), 6),
            'lift'            : round(float(row['lift']), 6),
            'strength'        : row.get('strength', ''),
            # v2 additions
            'composite_score' : round(float(row['composite_score']), 6),
            'revenue_weight'  : round(float(row.get('revenue_weight', 0)), 6),
            'score_tier'      : row.get('score_tier', ''),
            'is_cross_category': bool(row.get('is_cross_category', False))
        })

    cat_payload = []
    for _, row in cat_rules_df.nlargest(20, 'lift').iterrows():
        cat_payload.append({
            'rule_id'       : row['rule_id'],
            'antecedents'   : row['antecedents_str'],
            'consequents'   : row['consequents_str'],
            'support'       : round(float(row['support']), 6),
            'confidence'    : round(float(row['confidence']), 6),
            'lift'          : round(float(row['lift']), 6),
            'revenue_weight': round(float(row.get('revenue_weight', 0)), 6)
        })

    return {
        'event_type'    : 'Product_Associations_Updated',
        'agent_id'      : 'agent-05-basket-analysis',
        'kafka_topic'   : 'retail.intelligence.basket.associations',
        'schema_version': '2.0.0',
        'generated_at'  : datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ'),
        'metadata': {
            'model_version'           : 'v2',
            'total_rules_mined'       : int(len(rules_df)),
            'total_transactions'      : n_tx_valid,
            'products_covered'        : int(len(all_rule_items)),
            'variants_collapsed'      : 722,
            'min_support_threshold'   : MIN_SUPPORT_DYN,
            'min_confidence_threshold': MIN_CONFIDENCE,
            'min_lift_threshold'      : MIN_LIFT,
            'composite_score_weights' : {
                'lift': W_LIFT, 'confidence': W_CONFIDENCE,
                'revenue': W_REVENUE, 'zhang': W_ZHANG, 'leverage': W_LEVERAGE
            }
        },
        'top_item_rules'    : item_rules_payload,
        'category_rules'    : cat_payload,
        'downstream_agents' : ['agent-07-inventory-reorder', 'agent-01-pricing']
    }


kafka_payload = build_kafka_payload_v2(rules_export, cat_rules)
with open(paths['kafka'], 'w') as f:
    json.dump(kafka_payload, f, indent=2)

print('Kafka v2 payload saved.')
print()
print('Sample top rule from payload:')
print(json.dumps(kafka_payload['top_item_rules'][0], indent=4))

"""## Section 14 — Improvement 5: Enhanced Recommendation Engine

**Problem (v1):** The recommendation function required the antecedent to be a **strict subset** of the
query basket. If a query had 1 item but all strong rules had 2-item antecedents, no recommendations
were returned.

**Solution (v2):** Partial match scoring.
- Try exact antecedent match first (highest confidence)
- Fall back to partial matches, scored by `overlap_ratio × confidence × lift × revenue_weight`
- Rank final output by a business impact score that combines all signals
"""

# Load from disk so the recommendation engine is self-contained
try:
    rules_ui = pd.read_csv(paths['rules'])
    print(f'Rules loaded from disk: {len(rules_ui):,}')
except FileNotFoundError:
    rules_ui = rules_export.copy()
    print(f'Rules loaded from memory: {len(rules_ui):,}')


def get_recommendations_v2(
    query_products : list,
    rules_df       : pd.DataFrame,
    top_n          : int   = 10,
    min_lift       : float = 1.1,
    min_confidence : float = 0.10,
    min_overlap    : float = 0.5,      # partial match: at least 50% of antecedent must match
    cross_cat_only : bool  = False,
    use_composite  : bool  = True
) -> pd.DataFrame:
    """
    Enhanced recommendation function with partial match support.

    Parameters
    ----------
    query_products : list of canonical StockCodes currently in the basket
    rules_df       : data_basket_rules_v2.csv as DataFrame
    top_n          : number of recommendations
    min_lift       : minimum lift threshold
    min_confidence : minimum confidence threshold
    min_overlap    : minimum antecedent overlap fraction (0.5 = at least 50% must match)
    cross_cat_only : if True, return only cross-category recommendations
    use_composite  : if True, rank by composite_score; else rank by lift

    Returns
    -------
    DataFrame with ranked product recommendations and all scoring signals.
    """
    if rules_df.empty or not query_products:
        return pd.DataFrame()

    query_set = set(query_products)
    matched   = []

    for _, row in rules_df.iterrows():
        if row['lift'] < min_lift or row['confidence'] < min_confidence:
            continue
        if cross_cat_only and not row.get('is_cross_category', False):
            continue

        ant_items = set(row['antecedents_str'].split(', '))
        con_items = set(row['consequents_str'].split(', '))

        overlap      = ant_items & query_set
        overlap_ratio = len(overlap) / len(ant_items) if ant_items else 0

        if overlap_ratio < min_overlap:
            continue

        new_items = con_items - query_set
        if not new_items:
            continue

        # Adjusted confidence: scale by overlap ratio for partial matches
        adj_confidence = float(row['confidence']) * overlap_ratio

        # Business impact score
        rev_w      = float(row.get('revenue_weight', 0.1))
        comp_score = float(row.get('composite_score', 0.0))
        impact     = adj_confidence * float(row['lift']) * (1 + rev_w)

        for item in new_items:
            meta = canonical_meta.loc[item] if item in canonical_meta.index else None
            matched.append({
                'recommended_code'    : item,
                'recommended_desc'    : meta['base_desc'] if meta is not None else 'N/A',
                'category'            : meta['Category'] if meta is not None else 'N/A',
                'avg_price'           : round(meta['avg_price'], 2) if meta is not None else 0,
                'triggered_by_rule'   : row['rule_id'],
                'antecedents_matched' : ', '.join(sorted(overlap)),
                'overlap_ratio'       : round(overlap_ratio, 3),
                'support'             : round(float(row['support']), 5),
                'confidence'          : round(float(row['confidence']), 4),
                'adj_confidence'      : round(adj_confidence, 4),
                'lift'                : round(float(row['lift']), 4),
                'revenue_weight'      : round(rev_w, 4),
                'composite_score'     : round(comp_score, 4),
                'business_impact'     : round(impact, 4),
                'is_cross_category'   : bool(row.get('is_cross_category', False)),
                'score_tier'          : row.get('score_tier', '')
            })

    if not matched:
        return pd.DataFrame()

    sort_col = 'composite_score' if use_composite else 'lift'
    result   = (
        pd.DataFrame(matched)
        .sort_values(['business_impact', sort_col], ascending=False)
        .drop_duplicates('recommended_code')
        .head(top_n)
        .reset_index(drop=True)
    )
    result.index += 1
    return result


# Smoke test
sample_tx   = df_filtered.groupby('Invoice')['canonical_code'].apply(list).sample(1, random_state=7).iloc[0]
sample_query = sample_tx[:3]
print(f'Smoke test basket: {sample_query}')
smoke_result = get_recommendations_v2(sample_query, rules_ui, top_n=5)
if not smoke_result.empty:
    print(f'Recommendations: {len(smoke_result)}')
    print(smoke_result[['recommended_desc','overlap_ratio','confidence','lift','business_impact','score_tier']].to_string())
else:
    print('No recommendations for this basket — try the partial match UI below.')

"""## Section 15 — Interactive UI v2"""

# Build product option list from canonical metadata
product_options_sorted = sorted(
    f"{code} | {meta['base_desc'][:55]}"
    for code, meta in canonical_meta.iterrows()
)

# ── Widget definitions ─────────────────────────────────────────────────────
style_lbl    = {'description_width': '150px'}
layout_wide  = widgets.Layout(width='700px')
layout_med   = widgets.Layout(width='340px')

w_header = widgets.HTML("""
<div style='background:#0f3460;padding:16px 22px;border-radius:8px;margin-bottom:10px;'>
  <h2 style='color:#e0e0ff;margin:0;font-family:monospace;letter-spacing:1px;'>
    Agent 5 v2 — Market Basket Recommendation Engine
  </h2>
  <p style='color:#aac4ff;margin:6px 0 0 0;font-size:12px;'>
    FP-Growth | Variant-Normalized | Revenue-Weighted | Composite Scored | Partial Match
  </p>
</div>
""")

pickers = [
    widgets.Combobox(
        placeholder=f'Search product {i+1} {"(required)" if i==0 else "(optional)"}',
        options=product_options_sorted,
        description=f'Product {i+1}:',
        ensure_option=False, style=style_lbl, layout=layout_wide
    )
    for i in range(5)
]

w_topn        = widgets.IntSlider(value=10, min=1, max=30, description='Top N:', style=style_lbl, layout=layout_med)
w_lift        = widgets.FloatSlider(value=1.1, min=1.0, max=15.0, step=0.1, description='Min Lift:',
                                     readout_format='.1f', style=style_lbl, layout=layout_med)
w_conf        = widgets.FloatSlider(value=0.10, min=0.0, max=1.0, step=0.01, description='Min Confidence:',
                                     readout_format='.2f', style=style_lbl, layout=layout_med)
w_overlap     = widgets.FloatSlider(value=0.5, min=0.1, max=1.0, step=0.1, description='Min Overlap:',
                                     readout_format='.1f', style=style_lbl, layout=layout_med)
w_cross_only  = widgets.Checkbox(value=False, description='Cross-category only', style=style_lbl)
w_use_comp    = widgets.Checkbox(value=True,  description='Rank by composite score', style=style_lbl)

btn_run    = widgets.Button(description='Get Recommendations', button_style='success',
                            layout=widgets.Layout(width='180px', height='36px'))
btn_sample = widgets.Button(description='Load Sample Basket', button_style='info',
                            layout=widgets.Layout(width='160px', height='36px'))
btn_clear  = widgets.Button(description='Clear', button_style='warning',
                            layout=widgets.Layout(width='90px', height='36px'))
out = widgets.Output()


def parse_code(val):
    return val.split('|')[0].strip() if val and '|' in val else val.strip() if val else ''


def run_query(btn=None):
    with out:
        clear_output(wait=True)
        codes = [parse_code(p.value) for p in pickers if p.value.strip()]
        codes = [c for c in codes if c]
        if not codes:
            display(HTML("<p style='color:red;font-weight:bold;'>Enter at least one product.</p>"))
            return

        valid = [c for c in codes if c in canonical_meta.index]
        invalid = set(codes) - set(valid)
        if invalid:
            display(HTML(f"<p style='color:orange;font-size:12px;'>Warning: unknown code(s): {invalid}</p>"))
        if not valid:
            display(HTML("<p style='color:red;'>No valid canonical codes found.</p>"))
            return

        basket_html = ''.join(
            f"<tr><td style='padding:4px 12px;font-family:monospace;font-size:12px;'>{c}</td>"
            f"<td style='padding:4px 12px;'>{canonical_meta.loc[c,'base_desc']}</td>"
            f"<td style='padding:4px 12px;'>{canonical_meta.loc[c,'Category']}</td>"
            f"<td style='padding:4px 12px;text-align:right;'>£{canonical_meta.loc[c,'avg_price']:.2f}</td></tr>"
            for c in valid
        )
        display(HTML(f"""
        <div style='margin-bottom:12px;'>
          <b>Query Basket ({len(valid)} item(s)):</b>
          <table style='border-collapse:collapse;margin-top:6px;width:100%;font-size:13px;'>
            <thead><tr style='background:#0f3460;color:white;'>
              <th style='padding:5px 12px;text-align:left;'>StockCode</th>
              <th style='padding:5px 12px;text-align:left;'>Description</th>
              <th style='padding:5px 12px;text-align:left;'>Category</th>
              <th style='padding:5px 12px;text-align:right;'>Avg Price</th>
            </tr></thead>
            <tbody>{basket_html}</tbody>
          </table>
        </div>
        """))

        result = get_recommendations_v2(
            valid, rules_ui,
            top_n=w_topn.value,
            min_lift=w_lift.value,
            min_confidence=w_conf.value,
            min_overlap=w_overlap.value,
            cross_cat_only=w_cross_only.value,
            use_composite=w_use_comp.value
        )

        if result.empty:
            display(HTML("""
            <div style='padding:12px;background:#fff3cd;border-left:4px solid #ffc107;border-radius:4px;'>
              <b>No recommendations found.</b><br>
              <small>Try: lower Min Lift, lower Min Overlap, add more products, or uncheck Cross-category only.</small>
            </div>"""))
            return

        # Tier colors
        tier_colors = {'Tier 1':'#1a7a4a','Tier 2':'#2980b9','Tier 3':'#d68910','Tier 4':'#922b21','':'#777'}
        cross_color  = '#9B59B6'

        rows_html = ''
        for rank, (_, row) in enumerate(result.iterrows(), 1):
            tc   = tier_colors.get(row.get('score_tier',''), '#777')
            bg   = '#f9f9f9' if rank % 2 == 0 else 'white'
            xcat = (
                "<span style='background:#9B59B6;color:white;padding:1px 6px;border-radius:8px;font-size:10px;'>Cross-Cat</span>"
                if row.get('is_cross_category', False) else ''
            )
            rows_html += (
                f"<tr style='background:{bg};'>"
                f"<td style='padding:5px 8px;text-align:center;font-weight:bold;'>{rank}</td>"
                f"<td style='padding:5px 8px;font-family:monospace;font-size:11px;'>{row['recommended_code']}</td>"
                f"<td style='padding:5px 8px;'>{row['recommended_desc']} {xcat}</td>"
                f"<td style='padding:5px 8px;'>{row['category']}</td>"
                f"<td style='padding:5px 8px;text-align:right;'>£{row['avg_price']:.2f}</td>"
                f"<td style='padding:5px 8px;text-align:center;'>{row['overlap_ratio']:.0%}</td>"
                f"<td style='padding:5px 8px;text-align:center;'>{row['confidence']:.3f}</td>"
                f"<td style='padding:5px 8px;text-align:center;font-weight:bold;'>{row['lift']:.2f}</td>"
                f"<td style='padding:5px 8px;text-align:center;'>{row['revenue_weight']:.3f}</td>"
                f"<td style='padding:5px 8px;text-align:center;font-weight:bold;'>{row['business_impact']:.3f}</td>"
                f"<td style='padding:5px 8px;text-align:center;'>"
                f"<span style='background:{tc};color:white;padding:2px 7px;border-radius:10px;font-size:11px;'>{row.get('score_tier','')}</span>"
                f"</td></tr>"
            )

        display(HTML(f"""
        <b>Top {len(result)} Recommendations:</b>
        <table style='border-collapse:collapse;margin-top:6px;width:100%;font-size:12px;'>
          <thead><tr style='background:#0f3460;color:white;'>
            <th style='padding:5px 8px;'>#</th>
            <th style='padding:5px 8px;'>Code</th>
            <th style='padding:5px 8px;'>Product</th>
            <th style='padding:5px 8px;'>Category</th>
            <th style='padding:5px 8px;text-align:right;'>Price</th>
            <th style='padding:5px 8px;'>Overlap</th>
            <th style='padding:5px 8px;'>Conf</th>
            <th style='padding:5px 8px;'>Lift</th>
            <th style='padding:5px 8px;'>Rev.Wt</th>
            <th style='padding:5px 8px;'>Impact</th>
            <th style='padding:5px 8px;'>Tier</th>
          </tr></thead>
          <tbody>{rows_html}</tbody>
        </table>
        """))

        display(HTML(f"""
        <div style='margin-top:10px;display:flex;gap:16px;flex-wrap:wrap;'>
          <div style='padding:8px 14px;background:#e8f4fd;border-radius:6px;'><small>Avg Lift</small><br><b>{result['lift'].mean():.3f}</b></div>
          <div style='padding:8px 14px;background:#e8f8f5;border-radius:6px;'><small>Avg Confidence</small><br><b>{result['confidence'].mean():.3f}</b></div>
          <div style='padding:8px 14px;background:#fef9e7;border-radius:6px;'><small>Avg Impact</small><br><b>{result['business_impact'].mean():.3f}</b></div>
          <div style='padding:8px 14px;background:#fdf2f8;border-radius:6px;'><small>Avg Rev.Weight</small><br><b>{result['revenue_weight'].mean():.3f}</b></div>
          <div style='padding:8px 14px;background:#f0f3ff;border-radius:6px;'><small>Cross-Category</small><br><b>{result['is_cross_category'].sum()} / {len(result)}</b></div>
          <div style='padding:8px 14px;background:#f9f9f9;border-radius:6px;'><small>Results</small><br><b>{len(result)} / {w_topn.value}</b></div>
        </div>
        """))


def load_sample(btn=None):
    sample = df_filtered.groupby('Invoice')['canonical_code'].apply(list).sample(1, random_state=None).iloc[0]
    items  = list(set(sample))[:5]
    for p in pickers:
        p.value = ''
    for i, code in enumerate(items):
        if i < len(pickers) and code in canonical_meta.index:
            pickers[i].value = f"{code} | {canonical_meta.loc[code,'base_desc'][:55]}"


def clear_all(btn=None):
    for p in pickers:
        p.value = ''
    with out:
        clear_output(wait=True)


btn_run.on_click(run_query)
btn_sample.on_click(load_sample)
btn_clear.on_click(clear_all)

sep = widgets.HTML("<hr style='border:1px solid #ddd;margin:8px 0;'>")

ui = widgets.VBox([
    w_header,
    widgets.HTML("<b style='font-size:13px;'>Basket Products (up to 5)</b>"),
    *pickers,
    sep,
    widgets.HTML("<b style='font-size:13px;'>Filter Thresholds</b>"),
    widgets.HBox([w_topn, w_lift]),
    widgets.HBox([w_conf, w_overlap]),
    widgets.HBox([w_cross_only, w_use_comp]),
    sep,
    widgets.HBox([btn_run, btn_sample, btn_clear]),
    widgets.HTML('<br>'),
    out
], layout=widgets.Layout(padding='16px', max_width='950px'))

display(ui)

